name: "Build and full scan"

on:
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
    branches: [main]
    
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install Java
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'
            cache: 'gradle'

        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@v1

        - name: Build with Gradle
          run: ./gradlew assembleDebug --no-daemon --stacktrace

        - name: Upload application artifact
          uses: actions/upload-artifact@v2
          with:
            name: app
            path: ./app/build/outputs/apk/debug/app-debug.apk
            retention-days: 3
            
    scan:
      runs-on: ubuntu-latest
      outputs:
        report_id: ${{ steps.upload.outputs.report_id }}
      # The stage that builds the application.
      needs: build
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        # Replace with whatever pulls the application file before we upload.
        - name: Download application
          uses: actions/download-artifact@v2
          with:
          # Generated in the "build" stage.
            name: app

        - id: upload
          name: NowSecure upload app
          uses: nowsecure/nowsecure-action/upload-app@v3
          with:
            platform_token: ${{ secrets.NS_TOKEN }}
            # TODO: Replace application path.
            app_file:  "app-debug.apk"	
            # TODO: Replace the Group ID.
            group_id: "40f0f525-856d-4879-a694-4a8b0ee1d9dc"
            
    process:
        if: ${{ needs.scan.outputs.report_id }}
        runs-on: ubuntu-latest
        environment:
          name: nowsecure-env
        # The above stage we introduced.
        needs: scan
        
        # permission needed for upload-sarif@v2
        permissions:
          # required for all workflows
          security-events: write

        # only required for workflows in private repositories
          actions: read
          contents: read
      
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: NowSecure download report
            uses: nowsecure/nowsecure-action/convert-sarif@v3
            timeout-minutes: 30
            with:
              report_id: ${{ needs.scan.outputs.report_id }}
              platform_token: ${{ secrets.NS_TOKEN }}
              # TODO: Replace the Group ID.
              group_id: "40f0f525-856d-4879-a694-4a8b0ee1d9dc"
          
          - name: Save SARIF File
            uses: actions/upload-artifact@v2
            with:
              name: NowSecure SARIF
              path: NowSecure.sarif
              retention-days: 14

          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v2
            with:
              sarif_file: NowSecure.sarif

